name: Run mypy and pytest

on:
  push:
    branches:
      - main
      - release/*
  pull_request:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v3.3.0
      with:
        submodules: true
        lfs: true
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.1.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: install requirements.txt
      run: |
        pip install -r requirements.txt
    - name: install nanotune
      run: |
        pip install .
    - name: Run Mypy
      run: mypy nanotune
    - name: Run tests
      run: |
        pytest --cov=nanotune --cov=sim --cov=sim --cov-report xml --cov-config=setup.cfg
